version: '3.4'

services:
  eismokykla-api:
    image: node:15-alpine
    volumes:
      - type: bind
        source: ./
        target: /app
    working_dir: /app
    command: npm start
    ports:
      - '${PORT}:${PORT}'
      - '${DEBUG_PORT}:${DEBUG_PORT}'

    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
