version: '3.4'

services:
  todoListApi:
    image: node:15-alpine
    volumes:
      - type: bind
        source: ./
        target: /app
    working_dir: /app
    command: npm start
    ports:
      - '${PORT}:${PORT}'

    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
