version: '3.4'

services:
  todoListApi:
    image: node:15-alpine
    volumes:
      - type: bind
        source: ./
        target: /app
    working_dir: /app
    command: npm start
    ports:
      - '${PORT}:${PORT}'
      - '9229:9229'
    env_file:
      - .env
  mysql:
    image: mysql:8
    logging:
      driver: 'none'
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
